import { Bookmark } from "./types";

export const bookmarks: Bookmark[] = [
  {
    id: "figma",
    title: "Figma",
    domain: "figma.com",
    url: "https://figma.com",
    tag: "Design",
    categoryId: "cat_design",
    desc: "Collaborative interface design, prototyping, and dev handoff — all in the browser.",
    c1: "#a259ff",
    c2: "#f24e1e",
    fg: "#ffffff",
    glyph: "F",
    mins: 120,
    last: "2h ago",
    visits: 142,
    previewImage: null,
    likeCount: 0,
    likedByMe: false,
  },
  {
    id: "github",
    title: "GitHub",
    domain: "github.com",
    url: "https://github.com",
    tag: "Dev",
    categoryId: "cat_dev",
    desc: "Where the world builds software — host, review, and ship code together.",
    c1: "#9aa3ad",
    c2: "#d0d7de",
    fg: "#161616",
    glyph: "G",
    mins: 1440,
    last: "1d ago",
    visits: 210,
    previewImage: null,
    likeCount: 0,
    likedByMe: false,
  },
  {
    id: "stripe",
    title: "Stripe",
    domain: "stripe.com",
    url: "https://stripe.com",
    tag: "Finance",
    categoryId: "cat_design",
    desc: "Payments infrastructure for the internet — used by millions of businesses.",
    c1: "#635bff",
    c2: "#00d4ff",
    fg: "#ffffff",
    glyph: "S",
    mins: 4320,
    last: "3d ago",
    visits: 64,
    previewImage: null,
    likeCount: 0,
    likedByMe: false,
  },
];
